# Generated by Django 5.0.2 on 2024-02-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course_student_b_date_student_female_student_male_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='b_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='female',
        ),
        migrations.RemoveField(
            model_name='student',
            name='male',
        ),
        migrations.RemoveField(
            model_name='student',
            name='play',
        ),
    ]
